sudo: false
language: java
notifications:
  email: false
script:
  - ./thrillon/ceylonb compile-js --cwd=./thrillon
  - ./thrillon/ceylonb copy  --cwd=./thrillon --js --with-dependencies --include-language=true --out="./example/modules" herd.thrillon
  - ./example/ceylonb compile-js --cwd=./example
  - mkdir build
  - ./example/ceylonb copy --cwd=./example --js --with-dependencies --include-language=true --out="./build/modules" thrillon_example.client
  - cp -R ./example/index.html .example/require.js ./example/node_modules/ ./build/
env:
  global:
    - JAVA_OPTS="-Xmx3g"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
