sudo: false
language: java
notifications:
  email: false
script:
  - cd thrillon && ./ceylonb compile-js && cd ..
  - cd thrillon && ./ceylonb copy --js --with-dependencies --include-language=true --out="../example/modules" herd.thrillon && cd ..
  - cd example && ./ceylonb compile-js && cd ..
  - mkdir build
  - cd example && ./ceylonb copy --js --with-dependencies --include-language=true --out="../build/modules" thrillon_example.client && cd ..
  - cp -R ./example/index.html ./example/require.js ./example/node_modules/ ./build/
  - ls -R ./example/modules/thrillon_example/client/ 
  - cd ./example/ && cp -R modules/thrillon_example/client/*/module-resources/ ./build/ && cd ..
env:
  global:
    - JAVA_OPTS="-Xmx3g"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
